#!/usr/bin/env bash

[[ -e ~/.vim ]] && mv ~/.vim ~/.vim_$(date -u +%Y%m%d%H%M%S)
ln -s ~/dotfiles/vim ~/.vim
[[ -e ~/.vimrc ]] && mv ~/.vimrc ~/.vimrc_$(date -u +%Y%m%d%H%M%S)
ln -s ~/dotfiles/vim/rc ~/.vimrc
vim +BundleInstall +qall
echo 'vim linked'
